// Fixed UUIDs for reproducible demo data seeding
// All IDs are deterministic so repeated seeds produce the same records.

export const DEMO_COMPANY_ID = "00000000-0000-0000-0000-000000000001";

export const DEMO_USERS = [
  {
    email: "owner@demo.textile-os.com",
    password: "Demo@2026",
    full_name: "Rajesh Mehta",
    role: "factory_owner",
    department: "Management",
  },
  {
    email: "production@demo.textile-os.com",
    password: "Demo@2026",
    full_name: "Suresh Kumar",
    role: "production_manager",
    department: "Production",
  },
  {
    email: "merchandiser@demo.textile-os.com",
    password: "Demo@2026",
    full_name: "Priya Sharma",
    role: "merchandiser",
    department: "Merchandising",
  },
  {
    email: "quality@demo.textile-os.com",
    password: "Demo@2026",
    full_name: "Amit Patel",
    role: "quality_manager",
    department: "Quality",
  },
  {
    email: "purchase@demo.textile-os.com",
    password: "Demo@2026",
    full_name: "Deepak Joshi",
    role: "purchase_manager",
    department: "Purchase",
  },
  {
    email: "store@demo.textile-os.com",
    password: "Demo@2026",
    full_name: "Vikram Singh",
    role: "store_manager",
    department: "Store",
  },
  {
    email: "dyeing@demo.textile-os.com",
    password: "Demo@2026",
    full_name: "Ravi Desai",
    role: "dyeing_master",
    department: "Dyeing",
  },
  {
    email: "finance@demo.textile-os.com",
    password: "Demo@2026",
    full_name: "Neha Gupta",
    role: "finance_manager",
    department: "Accounts",
  },
];

export const DEMO_BUYERS = [
  {
    name: "H&M Trading",
    code: "BYR-HM",
    contact_person: "Anna Lindqvist",
    email: "sourcing@hm.example.com",
    phone: "+46-8-796-5500",
    city: "Stockholm",
    country: "Sweden",
    payment_terms: "TT 60 Days",
    quality_standard: "AQL 2.5",
    default_currency: "USD",
  },
  {
    name: "Zara International",
    code: "BYR-ZARA",
    contact_person: "Carlos Rodriguez",
    email: "buying@zara.example.com",
    phone: "+34-981-185-400",
    city: "A Coruna",
    country: "Spain",
    payment_terms: "LC 45 Days",
    quality_standard: "AQL 1.5",
    default_currency: "EUR",
  },
  {
    name: "Target Corporation",
    code: "BYR-TGT",
    contact_person: "Sarah Johnson",
    email: "imports@target.example.com",
    phone: "+1-612-304-6073",
    city: "Minneapolis",
    country: "USA",
    payment_terms: "TT 45 Days",
    quality_standard: "AQL 2.5",
    default_currency: "USD",
  },
  {
    name: "Primark Stores",
    code: "BYR-PRM",
    contact_person: "James O'Brien",
    email: "sourcing@primark.example.com",
    phone: "+353-1-888-1234",
    city: "Dublin",
    country: "Ireland",
    payment_terms: "TT 30 Days",
    quality_standard: "AQL 4.0",
    default_currency: "GBP",
  },
  {
    name: "Next Plc",
    code: "BYR-NEXT",
    contact_person: "Emily Watson",
    email: "buying@next.example.com",
    phone: "+44-845-600-7000",
    city: "Leicester",
    country: "UK",
    payment_terms: "TT 60 Days",
    quality_standard: "AQL 2.5",
    default_currency: "GBP",
  },
];

export const DEMO_SUPPLIERS = [
  {
    name: "Vardhman Textiles Ltd",
    code: "SUP-VRDH",
    contact_person: "Arun Goyal",
    email: "sales@vardhman.example.com",
    city: "Ludhiana",
    country: "India",
    material_types: ["yarn", "fabric"],
    avg_lead_time_days: 14,
    rating: 8.5,
  },
  {
    name: "Alok Industries",
    code: "SUP-ALOK",
    contact_person: "Pankaj Shah",
    email: "export@alok.example.com",
    city: "Mumbai",
    country: "India",
    material_types: ["fabric"],
    avg_lead_time_days: 10,
    rating: 7.8,
  },
  {
    name: "SRF Polymers",
    code: "SUP-SRF",
    contact_person: "Manoj Kumar",
    email: "sales@srf.example.com",
    city: "Gurgaon",
    country: "India",
    material_types: ["yarn"],
    avg_lead_time_days: 7,
    rating: 9.0,
  },
  {
    name: "YKK India",
    code: "SUP-YKK",
    contact_person: "Takeshi Yoshida",
    email: "india@ykk.example.com",
    city: "Faridabad",
    country: "India",
    material_types: ["trims"],
    avg_lead_time_days: 5,
    rating: 9.2,
  },
  {
    name: "Archroma India",
    code: "SUP-ARCH",
    contact_person: "Rajan Nair",
    email: "orders@archroma.example.com",
    city: "Thane",
    country: "India",
    material_types: ["chemicals"],
    avg_lead_time_days: 3,
    rating: 8.8,
  },
  {
    name: "Grasim Industries",
    code: "SUP-GRSM",
    contact_person: "Rahul Bhatt",
    email: "viscose@grasim.example.com",
    city: "Mumbai",
    country: "India",
    material_types: ["yarn", "fabric"],
    avg_lead_time_days: 12,
    rating: 8.2,
  },
  {
    name: "Coats India",
    code: "SUP-COAT",
    contact_person: "Sunil Mehta",
    email: "sales@coats.example.com",
    city: "Bangalore",
    country: "India",
    material_types: ["trims"],
    avg_lead_time_days: 4,
    rating: 9.1,
  },
  {
    name: "Huntsman Textile",
    code: "SUP-HUNT",
    contact_person: "Michael Chen",
    email: "asia@huntsman.example.com",
    city: "Shanghai",
    country: "China",
    material_types: ["chemicals"],
    avg_lead_time_days: 15,
    rating: 7.5,
  },
];

export const DEMO_COLORS = [
  { name: "Black", code: "BLK", pantone_ref: "19-0303 TCX", hex_code: "#1C1C1C" },
  { name: "White", code: "WHT", pantone_ref: "11-0601 TCX", hex_code: "#FFFFFF" },
  { name: "Navy Blue", code: "NVY", pantone_ref: "19-4052 TCX", hex_code: "#1B2A4A" },
  { name: "Red", code: "RED", pantone_ref: "18-1763 TCX", hex_code: "#C5282F" },
  { name: "Olive Green", code: "OLV", pantone_ref: "18-0527 TCX", hex_code: "#6B7F3E" },
  { name: "Charcoal Grey", code: "CHR", pantone_ref: "18-0601 TCX", hex_code: "#4A4A4A" },
  { name: "Royal Blue", code: "RYL", pantone_ref: "19-3955 TCX", hex_code: "#2B4E96" },
  { name: "Burgundy", code: "BRG", pantone_ref: "19-1726 TCX", hex_code: "#722F37" },
  { name: "Forest Green", code: "FGR", pantone_ref: "19-5513 TCX", hex_code: "#2C5F2D" },
  { name: "Coral", code: "CRL", pantone_ref: "16-1546 TCX", hex_code: "#FF6F61" },
  { name: "Mustard", code: "MST", pantone_ref: "15-1054 TCX", hex_code: "#D4A017" },
  { name: "Teal", code: "TEL", pantone_ref: "17-4919 TCX", hex_code: "#008080" },
  { name: "Slate Blue", code: "SLT", pantone_ref: "17-4015 TCX", hex_code: "#6A8CA8" },
  { name: "Dusty Rose", code: "DSR", pantone_ref: "15-1515 TCX", hex_code: "#C4867C" },
  { name: "Ivory", code: "IVR", pantone_ref: "11-0507 TCX", hex_code: "#F5F1E4" },
  { name: "Khaki", code: "KHK", pantone_ref: "16-1324 TCX", hex_code: "#C3B091" },
  { name: "Sky Blue", code: "SKY", pantone_ref: "14-4318 TCX", hex_code: "#87CEEB" },
  { name: "Peach", code: "PCH", pantone_ref: "14-1228 TCX", hex_code: "#FFCBA4" },
  { name: "Lavender", code: "LAV", pantone_ref: "14-3812 TCX", hex_code: "#B57EDC" },
  { name: "Beige", code: "BGE", pantone_ref: "13-1009 TCX", hex_code: "#D4C5A9" },
];

export const DEMO_SIZES = [
  { name: "XS", code: "XS", sort_order: 1 },
  { name: "S", code: "S", sort_order: 2 },
  { name: "M", code: "M", sort_order: 3 },
  { name: "L", code: "L", sort_order: 4 },
  { name: "XL", code: "XL", sort_order: 5 },
  { name: "XXL", code: "XXL", sort_order: 6 },
];

export const DEMO_FABRICS = [
  { name: "Cotton Jersey 180 GSM", code: "FAB-CJ180", fabric_type: "knitted", gsm: 180, width_cm: 150, composition: "100% Cotton", uom: "kg", rate: 450 },
  { name: "Cotton Pique 220 GSM", code: "FAB-CP220", fabric_type: "knitted", gsm: 220, width_cm: 155, composition: "100% Cotton", uom: "kg", rate: 520 },
  { name: "PC Single Jersey 160 GSM", code: "FAB-PC160", fabric_type: "knitted", gsm: 160, width_cm: 150, composition: "60/40 PC", uom: "kg", rate: 380 },
  { name: "Cotton Rib 1x1 220 GSM", code: "FAB-RIB220", fabric_type: "knitted", gsm: 220, width_cm: 80, composition: "100% Cotton", uom: "kg", rate: 480 },
  { name: "Cotton Poplin 120 GSM", code: "FAB-POP120", fabric_type: "woven", gsm: 120, width_cm: 145, construction: "60x60/20x20", composition: "100% Cotton", uom: "meter", rate: 210 },
  { name: "Cotton Twill 200 GSM", code: "FAB-TW200", fabric_type: "woven", gsm: 200, width_cm: 145, construction: "2/1 Twill", composition: "100% Cotton", uom: "meter", rate: 280 },
  { name: "Denim 12oz", code: "FAB-DNM12", fabric_type: "woven", gsm: 400, width_cm: 150, construction: "3/1 Twill", composition: "100% Cotton", uom: "meter", rate: 350 },
  { name: "Viscose Rayon 140 GSM", code: "FAB-VR140", fabric_type: "woven", gsm: 140, width_cm: 145, composition: "100% Viscose", uom: "meter", rate: 190 },
  { name: "Cotton Fleece 320 GSM", code: "FAB-FL320", fabric_type: "knitted", gsm: 320, width_cm: 160, composition: "80/20 CVC", uom: "kg", rate: 560 },
  { name: "Interlock 200 GSM", code: "FAB-INT200", fabric_type: "knitted", gsm: 200, width_cm: 155, composition: "100% Cotton", uom: "kg", rate: 500 },
];

export const DEMO_PRODUCTS = [
  { name: "Classic Crew Neck T-Shirt", style_code: "STY-CRW01", category: "T-shirt" },
  { name: "Slim Fit V-Neck Tee", style_code: "STY-VNK01", category: "T-shirt" },
  { name: "Polo Shirt with Tipping", style_code: "STY-POL01", category: "Polo" },
  { name: "Button Down Oxford Shirt", style_code: "STY-OXF01", category: "Shirt" },
  { name: "Slim Fit Chino Trouser", style_code: "STY-CHN01", category: "Trouser" },
  { name: "Zip-Up Hoodie", style_code: "STY-HOD01", category: "Hoodie" },
  { name: "French Terry Sweatshirt", style_code: "STY-SWT01", category: "Sweatshirt" },
  { name: "Athletic Shorts", style_code: "STY-SHR01", category: "Shorts" },
  { name: "Summer Shift Dress", style_code: "STY-DRS01", category: "Dress" },
  { name: "Tank Top Basic", style_code: "STY-TNK01", category: "Tank Top" },
  { name: "Cargo Jogger Pant", style_code: "STY-JOG01", category: "Trouser" },
  { name: "Henley Neck T-Shirt", style_code: "STY-HNL01", category: "T-shirt" },
  { name: "Trucker Denim Jacket", style_code: "STY-JKT01", category: "Jacket" },
  { name: "Linen Blend Camp Shirt", style_code: "STY-CMP01", category: "Shirt" },
  { name: "Raglan Sleeve Baseball Tee", style_code: "STY-RGL01", category: "T-shirt" },
];

export const DEMO_PRODUCTION_LINES = [
  { name: "Line 1", department: "sewing", total_operators: 35, target_per_hour: 100 },
  { name: "Line 2", department: "sewing", total_operators: 38, target_per_hour: 110 },
  { name: "Line 3", department: "sewing", total_operators: 32, target_per_hour: 95 },
  { name: "Line 4", department: "sewing", total_operators: 30, target_per_hour: 85 },
  { name: "Line 5", department: "sewing", total_operators: 36, target_per_hour: 105 },
  { name: "Line 6", department: "sewing", total_operators: 34, target_per_hour: 100 },
  { name: "Line 7", department: "finishing", total_operators: 20, target_per_hour: 150 },
  { name: "Line 8", department: "finishing", total_operators: 15, target_per_hour: 120 },
];

export const DEMO_DEPARTMENTS = [
  "Merchandising",
  "Production",
  "Cutting",
  "Sewing",
  "Finishing",
  "Quality",
  "Store",
  "Dyeing",
  "Shipping",
  "Accounts",
  "HR",
  "Maintenance",
  "Admin",
];

export const DEMO_NUMBER_SERIES = [
  { document_type: "sales_order", prefix: "SO" },
  { document_type: "purchase_order", prefix: "PO" },
  { document_type: "grn", prefix: "GRN" },
  { document_type: "work_order", prefix: "WO" },
  { document_type: "inquiry", prefix: "INQ" },
  { document_type: "sample", prefix: "SA" },
  { document_type: "lab_dip", prefix: "LD" },
  { document_type: "inspection", prefix: "QC" },
  { document_type: "shipment", prefix: "SH" },
  { document_type: "cost_sheet", prefix: "CS" },
  { document_type: "capa", prefix: "CA" },
  { document_type: "dyeing_batch", prefix: "DB" },
  { document_type: "material_request", prefix: "MR" },
];
